### ISSUE TITLE
Document (or implement?) socket repls?

### ISSUE THREAD

**Issue by halgari** [nasser/nostrand#11]
I can't seem to connect to the built-in `nos` socket repl. I'm using telnet, and maybe I should be using something else. ClojureCLR also supports the Clojure socket repl in `clojure.core.server`. Would you be open to adding a task to `nos` that would fire off `clojure.core.server/repl`? If so I can probably create a PR for it.

**Comment by nasser** [comment]
telnet probably wont cut it. It's a UDP repl based on Arcadia's. I would be open to a `clojure.core.server/repl` PR for sure!
