### ISSUE TITLE
*load-path* not getting set correctly

### ISSUE THREAD

**Issue by nasser** [nasser/nostrand#27]
The current directory does not ever get added to the load path it seems

**Comment by skydread1** [comment]
The current directory was added to the load path in my case when I added a `project.edn`
After the `dotnet build`, I cd to a clojure project.
I added the following `project.edn` :

```
{:name "loic exos"
 :source-paths ["src" "test"]
 :dependencies [[:github nasser/test.check "master"]]}
```

I then run the `nos mytasks/build` command with `mytasks.clj` being :
```
(ns mytasks)

(defn build []
  (binding [*compile-path* "build"]
    (compile 'flybot.loic-exos)
    (compile 'flybot.loic-exos-test)))
```

The `load-path` is the the following : 
```
[/Users/loicblanchard/workspaces/loic-exos /Users/loicblanchard/workspaces/loic-exos/src /Users/loicblanchard/workspaces/loic-exos/test /Users/loicblanchard/workspaces/loic-exos /Users/loicblanchard/workspaces/loic-exos/src /Users/loicblanchard/workspaces/nostrand/bin/x64/Debug/net471]
```

There are some redundancies though.

The 2 dlls are generated but in 2 different locations
- in the expected `/build` folder
- at the root of the clojure project

**Comment by nasser** [comment]
The current directory is now always on the load path. I could not reproduce your other issue though @skydread1. I only get a compiled dll in the `build` directory. Can you try again with the latest nostrand?
